language: node_js
node_js:
  - "node"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
deploy:
  provider: firebase
    project: "q-bot-test-7d5cb"
    branches:
      only:
        - master
